add go.sum (#90)

diff --git a/test_all b/test_all
--- a/test_all
+++ b/test_all
@@ -19,8 +19,8 @@ printf "OK\n"
 
 printf "Running 'go install'..."
 go_install_output=`go install 2>&1`
-if [if [ "$?" -ne "0" ]; then
-    printf "FAIL. output:\n$go_install_output" 1>&2
+if [ "$?" -ne "0" ]; then
+    printf "FAIL. output:\n$go_install_output\n" 1>&2
     exit 1
 fi
 printf "OK\n"
@@ -29,7 +29,7 @@ printf "Running go vet tests..."
 go_vet_output="$(go vet -v ./... 2>&1 | grep ':' )"
 # grep ':' is a hack-ish way to only match path/to/file.go:lineno:colno: vet msg
 if [ ! -z "$go_vet_output" ]; then
-    printf "FAIL. output:\n$go_vet_output" 1>&2
+    printf "FAIL. output:\n$go_vet_output\n" 1>&2
     exit 1
 fi
 printf "OK\n"
